In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [419]:
df_ = pd.read_excel('/Users/huseyinefkanalp/Desktop/DataScience/DataSets/2021-2022Football.xls')

In [461]:
df = df_.copy()
df.fillna(0.0, inplace = True)

## Defans
---

In [462]:
df.reset_index(inplace=True)

/var/folders/d4/wz2dgkvx2bl0sj81mlfhmt1r0000gn/T/ipykernel_2582/136303746.py:1: PerformanceWarning:

DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

In [463]:
df.rename({"index": "Id"}, axis="columns", inplace = True)

In [464]:
df.head()

,Id,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Goals,Shots,SoT,SoT%,G/Sh,G/SoT,ShoDist,ShoFK,ShoPK,PKatt,PasTotCmp,PasTotAtt,PasTotCmp%,PasTotDist,PasTotPrgDist,PasShoCmp,PasShoAtt,PasShoCmp%,PasMedCmp,PasMedAtt,PasMedCmp%,PasLonCmp,PasLonAtt,PasLonCmp%,Assists,PasAss,Pas3rd,PPA,CrsPA,PasProg,PasAtt,PasLive,PasDead,PasFK,TB,PasPress,Sw,PasCrs,CK,CkIn,CkOut,CkStr,PasGround,PasLow,PasHigh,PaswLeft,PaswRight,PaswHead,TI,PaswOther,PasCmp,PasOff,PasOut,PasInt,PasBlocks,SCA,ScaPassLive,ScaPassDead,ScaDrib,ScaSh,ScaFld,ScaDef,GCA,GcaPassLive,GcaPassDead,GcaDrib,GcaSh,GcaFld,GcaDef,Tkl,TklWon,TklDef3rd,TklMid3rd,TklAtt3rd,TklDri,TklDriAtt,TklDri%,TklDriPast,Press,PresSucc,Press%,PresDef3rd,PresMid3rd,PresAtt3rd,Blocks,BlkSh,BlkShSv,BlkPass,Int,Tkl+Int,Clr,Err,Touches,TouDefPen,TouDef3rd,TouMid3rd,TouAtt3rd,TouAttPen,TouLive,DriSucc,DriAtt,DriSucc%,DriPast,DriMegs,Carries,CarTotDist,CarPrgDist,CarProg,Car3rd,CPA,CarMis,CarDis,RecTarg,Rec,Rec%,RecProg,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
0,0,Max Aarons,ENG,DF,Norwich City,Premier League,22.0000,2000,34,32,2881,32,0.0000,0.41,0.06,15.Nis,0,0,20.May,0.0000,0,0,34,45,755,5741,214.8,17.May,19.Nis,90,13.Oca,17,77.0000,3.Haz,Haz.78,45.2,0.06,0.59,Oca.56,Oca.13,0.25,Şub.94,45,34.4,10.Haz,0.84,0.06,May.41,0.59,Oca.41,0,0,0,0.0000,26.May,Eyl.59,Ağu.94,Nis.91,29,0.91,Eyl.72,0.06,34,22.0000,0.88,Oca.63,Oca.75,Oca.19,0.84,0.06,9.0000,0.13,0.06,0.0000,0.16,0.16,0.0000,0,0.0000,0.0000,0,Şub.16,Oca.16,Oca.56,0.59,0,Oca.16,Oca.81,63.8,0.66,13.Haz,Mar.53,26,Tem.97,Nis.38,Oca.22,Şub.69,0.69,3,2,Oca.75,Mar.91,Şub.19,0,58,5.Haz,23.Mar,23.Ağu,15,0.91,47.8,1.Mar,Şub.44,42.3,1.Eyl,19.0000,33.9,1994.0000,121.7,May.44,Oca.66,0.41,0.84,0.94,36,32.4,899.0000,Oca.28,0.25,0.0000,0.0000,0.97,Oca.84,0.03,Oca.41,Oca.16,0.0000,6.0000,3,May.53,0.47,Oca.59,22.Tem
1,1,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,34.0000,1987,34,34,2983,33.1,6.0000,0.54,0.18,33.3,11,33,18.Tem,0.0000,0,0,38.7,47,824,8358,287.9,10.Şub,11.Nis,899,22.Nis,25,894.0000,May.65,Eyl.15,61.7,0,0.24,Şub.45,0.18,0,Şub.72,47,44,3.Şub,Şub.45,0,May.68,Oca.66,0.06,0,0,0,0.0000,35.3,Mar.78,Tem.95,31.Tem,12.Oca,Oca.48,0.42,0.12,38.7,15.0000,0.97,Oca.24,0.88,0.63,0.42,0,9.0000,0.03,0,9.0000,0.03,0,0.0000,3,0.0000,0.0000,0,Oca.87,Oca.39,Oca.24,0.6,0.03,0.39,0.82,48.1,0.42,13.Haz,Nis.89,35.9,Tem.61,May.14,0.88,Oca.87,0.79,6,1.Eyl,3.Kas,Nis.98,3.Şub,0,57.3,Ağu.28,32.8,25.Tem,2.Eyl,0.85,54.5,0.48,0.66,72.7,0.48,3.0000,35.7,2047.0000,115.5,Şub.75,0.73,0,0.45,0.39,37.5,36.3,969.0000,0.36,0.15,3.0000,0.0000,1.Mar,0.73,0,0.06,Oca.39,0.0000,3.0000,0,Haz.77,2.Şub,Oca.36,59.8
2,2,Salis Abdul Samed,GHA,MF,Clermont Foot,Ligue 1,22.0000,2000,31,29,2462,27.Nis,4.0000,0.66,0.18,27.Ağu,6,2,20.Mar,0.0000,0,0,55.9,61,917,10333,184.4,22.May,24.Oca,935,25.Ağu,27.Şub,949.0000,Haz.72,Tem.81,86,0,0.55,Şub.81,0.47,0.04,Şub.96,61,60.3,0.73,0.58,0.04,8.Mar,0.8,0.36,0,0,0,0.0000,52.6,Nis.71,Mar.72,Nis.82,53.1,1.Eyl,0.15,0.29,55.9,7.0000,0.58,Oca.24,0.84,Oca.46,1.Eyl,0,0.0000,0.15,0.15,7.0000,0.04,0.04,0.0000,0,0.0000,0.0000,0,2.Oca,Oca.24,0.91,0.91,0.18,0.69,Şub.15,32.2,Oca.46,23.Nis,Haz.53,27.Eyl,Tem.19,12.Mar,Mar.94,0.99,0.04,0,0.95,Oca.86,Mar.87,0.55,0,70.4,2.Oca,22.Tem,41.8,10.Eyl,0.62,69.9,0.99,Oca.53,64.3,1.Eyl,7.0000,53.5,2465.0000,106.3,Şub.85,0.73,0.15,0.84,Oca.46,58.6,54.2,925.0000,Oca.72,0.44,11.0000,7.0000,Oca.64,Oca.28,0,0.36,Oca.24,0.0000,0.0000,0,Ağu.76,0.88,0.88,50
3,3,Laurent Abergel,FRA,MF,Lorient,Ligue 1,29.0000,1993,34,34,2956,32.8,0.0000,0.91,0.21,23.Mar,0,0,22.Haz,0.0000,0,0,40.7,49.8,816,7808,206,16.Mar,18.Nis,886,17.Mar,19.Haz,879.0000,Haz.25,Eyl.39,66.6,0.06,0.91,Mar.87,0.58,0.18,Nis.18,49.8,49,0.85,0.64,0.18,Eyl.48,Oca.49,0.79,0.03,0,0,0.0000,37.6,May.64,Haz.65,Nis.48,43.9,0.73,0.15,0.15,40.7,21.0000,0.55,Oca.83,Oca.68,2.Oca,Oca.49,0.06,3.0000,0.03,0.21,18.0000,0.15,0.12,0.0000,0,0.0000,3.0000,0,Mar.57,Şub.23,Oca.49,Oca.71,0.37,1.Ağu,Nis.97,36.2,Mar.17,28,7.Eyl,28.Şub,Eyl.27,15.Mar,Mar.41,Oca.68,0.09,0,Oca.59,Şub.56,Haz.13,0.34,0,61.6,0.67,13.Tem,40.3,11.Haz,0.46,60.9,Oca.28,Oca.98,64.6,Oca.34,9.0000,45.7,1719.0000,86.4,Şub.87,Oca.13,0.09,0.85,Oca.46,46.3,43,93.0000,Oca.86,0.27,0.0000,0.0000,1.Nis,2.Tem,0.03,0.79,Şub.23,0.0000,0.0000,0,Ağu.87,0.43,0.43,50
4,4,Charles Abi,FRA,FW,Saint-…tienne,Ligue 1,22.0000,2000,1,1,45,0.5,0.0000,0,0,0,0,0,0,0.0000,0,0,4,12,333,48,0,2,4,50,2,6,333.0000,0,0,0,0,0,0,0,0,0,12,12,0,0,0,6,0,2,0,0,0,0.0000,10,0,2,12,0,0,0,0,4,0.0000,0,4,0,0,0,0,0.0000,0,0,0.0000,0,0,0.0000,0,0.0000,0.0000,0,0,0,0,0,0,0,2,0,2,28,2,7.Oca,0,22,6,2,0,0,2,0,0,0,0,24,0,0,10,18,6,24,0,0,0,0,0.0000,18,118.0000,18,0,2,0,8,0,24,16,667.0000,4,0,0.0000,0.0000,2,0,0,2,0,0.0000,0.0000,0,4,2,0,100

In [465]:
info_df = pd.DataFrame()
info_df["Id"] = df["Id"]
info_df["Name"] = df["Player"]
info_df["Nation"] = df["Nation"]
info_df["Team"] = df["Squad"]
info_df["League"] = df["Comp"]
info_df["Born"] = df["Born"]
info_df["Mac"] = df["MP"]

In [466]:
info_df.head()

   Id               Name Nation           Team          League  Born  Mac
0   0         Max Aarons    ENG   Norwich City  Premier League  2000   34
1   1   Yunis Abdelhamid    MAR          Reims         Ligue 1  1987   34
2   2  Salis Abdul Samed    GHA  Clermont Foot         Ligue 1  2000   31
3   3    Laurent Abergel    FRA        Lorient         Ligue 1  1993   34
4   4        Charles Abi    FRA  Saint-…tienne         Ligue 1  2000    1

In [467]:
df.drop(["Player","Nation","Squad","Comp","Born","MP"],inplace = True, axis = 1)

In [468]:
for i in df.columns:
    if i == "Pos":
        continue
    else:
        df[i] = pd.to_numeric(df[i], errors='coerce')

In [469]:
df.head()

,Id,Pos,Age,Starts,Min,90s,Goals,Shots,SoT,SoT%,G/Sh,G/SoT,ShoDist,ShoFK,ShoPK,PKatt,PasTotCmp,PasTotAtt,PasTotCmp%,PasTotDist,PasTotPrgDist,PasShoCmp,PasShoAtt,PasShoCmp%,PasMedCmp,PasMedAtt,PasMedCmp%,PasLonCmp,PasLonAtt,PasLonCmp%,Assists,PasAss,Pas3rd,PPA,CrsPA,PasProg,PasAtt,PasLive,PasDead,PasFK,TB,PasPress,Sw,PasCrs,CK,CkIn,CkOut,CkStr,PasGround,PasLow,PasHigh,PaswLeft,PaswRight,PaswHead,TI,PaswOther,PasCmp,PasOff,PasOut,PasInt,PasBlocks,SCA,ScaPassLive,ScaPassDead,ScaDrib,ScaSh,ScaFld,ScaDef,GCA,GcaPassLive,GcaPassDead,GcaDrib,GcaSh,GcaFld,GcaDef,Tkl,TklWon,TklDef3rd,TklMid3rd,TklAtt3rd,TklDri,TklDriAtt,TklDri%,TklDriPast,Press,PresSucc,Press%,PresDef3rd,PresMid3rd,PresAtt3rd,Blocks,BlkSh,BlkShSv,BlkPass,Int,Tkl+Int,Clr,Err,Touches,TouDefPen,TouDef3rd,TouMid3rd,TouAtt3rd,TouAttPen,TouLive,DriSucc,DriAtt,DriSucc%,DriPast,DriMegs,Carries,CarTotDist,CarPrgDist,CarProg,Car3rd,CPA,CarMis,CarDis,RecTarg,Rec,Rec%,RecProg,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
0,0,DF,22.0000,32,2881,32.0000,0.0000,0.4100,0.0600,NaN,0,0,NaN,0.0000,0,0,34.0000,45.0000,755,5741,214.8000,NaN,NaN,90,NaN,17.0000,77.0000,NaN,NaN,45.2000,0.0600,0.5900,NaN,NaN,0.2500,NaN,45.0000,34.4000,NaN,0.8400,0.0600,NaN,0.5900,NaN,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,29.0000,0.9100,NaN,0.0600,34.0000,22.0000,0.8800,NaN,NaN,NaN,0.8400,0.0600,9.0000,0.1300,0.0600,0.0000,0.1600,0.1600,0.0000,0,0.0000,0.0000,0,NaN,NaN,NaN,0.5900,0.0000,NaN,NaN,63.8000,0.6600,NaN,NaN,26.0000,NaN,NaN,NaN,NaN,0.6900,3,2.0000,NaN,NaN,NaN,0.0000,58.0000,NaN,NaN,NaN,15.0000,0.9100,47.8000,NaN,NaN,42.3000,NaN,19.0000,33.9000,1994.0000,121.7000,NaN,NaN,0.4100,0.8400,0.9400,36.0000,32.4000,899.0000,NaN,0.2500,0.0000,0.0000,0.9700,NaN,0.0300,NaN,NaN,0.0000,6.0000,3,NaN,0.4700,NaN,NaN
1,1,DF,34.0000,34,2983,33.1000,6.0000,0.5400,0.1800,33.3000,11,33,NaN,0.0000,0,0,38.7000,47.0000,824,8358,287.9000,NaN,NaN,899,NaN,25.0000,894.0000,NaN,NaN,61.7000,0.0000,0.2400,NaN,0.1800,0.0000,NaN,47.0000,44.0000,NaN,NaN,0.0000,NaN,NaN,0.0600,0.0000,0.0000,0.0000,0.0000,35.3000,NaN,NaN,NaN,NaN,NaN,0.4200,0.1200,38.7000,15.0000,0.9700,NaN,0.8800,0.6300,0.4200,0.0000,9.0000,0.0300,0.0000,9.0000,0.0300,0.0000,0.0000,3,0.0000,0.0000,0,NaN,NaN,NaN,0.6000,0.0300,0.3900,0.8200,48.1000,0.4200,NaN,NaN,35.9000,NaN,NaN,0.8800,NaN,0.7900,6,NaN,NaN,NaN,NaN,0.0000,57.3000,NaN,32.8000,NaN,NaN,0.8500,54.5000,0.4800,0.6600,72.7000,0.4800,3.0000,35.7000,2047.0000,115.5000,NaN,0.7300,0.0000,0.4500,0.3900,37.5000,36.3000,969.0000,0.3600,0.1500,3.0000,0.0000,NaN,0.7300,0.0000,0.0600,NaN,0.0000,3.0000,0,NaN,NaN,NaN,59.8000
2,2,MF,22.0000,29,2462,NaN,4.0000,0.6600,0.1800,NaN,6,2,NaN,0.0000,0,0,55.9000,61.0000,917,10333,184.4000,NaN,NaN,935,NaN,NaN,949.0000,NaN,NaN,86.0000,0.0000,0.5500,NaN,0.4700,0.0400,NaN,61.0000,60.3000,0.7300,0.5800,0.0400,NaN,0.8000,0.3600,0.0000,0.0000,0.0000,0.0000,52.6000,NaN,NaN,NaN,53.1000,NaN,0.1500,0.2900,55.9000,7.0000,0.5800,NaN,0.8400,NaN,NaN,0.0000,0.0000,0.1500,0.1500,7.0000,0.0400,0.0400,0.0000,0,0.0000,0.0000,0,NaN,NaN,0.9100,0.9100,0.1800,0.6900,NaN,32.2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9900,0.0400,0,0.9500,NaN,NaN,0.5500,0.0000,70.4000,NaN,NaN,41.8000,NaN,0.6200,69.9000,0.9900,NaN,64.3000,NaN,7.0000,53.5000,2465.0000,106.3000,NaN,0.7300,0.1500,0.8400,NaN,58.6000,54.2000,925.0000,NaN,0.4400,11.0000,7.0000,NaN,NaN,0.0000,0.3600,NaN,0.0000,0.0000,0,NaN,0.8800,0.8800,50.0000
3,3,MF,29.0000,34,2956,32.8000,0.0000,0.9100,0.2100,NaN,0,0,NaN,0.0000,0,0,40.7000,49.8000,816,7808,206.0000,NaN,NaN,886,NaN,NaN,879.0000,NaN,NaN,66.6000,0.0600,0.9100,NaN,0.5800,0.1800,NaN,49.8000,49.0000,0.8500,0.6400,0.1800,NaN,NaN,0.7900,0.0300,0.0000,0.0000,0.0000,37.6000,NaN,NaN,NaN,43.9000,0.7300,0.1500,0.1500,40.7000,21.0000,0.5500,NaN,NaN,NaN,NaN,0.0600,3.0000,0.0300,0.2100,18.0000,0.1500,0.1200,0.0000,0,0.0000,3.0000,0,NaN,NaN,NaN,NaN,0.3700,NaN,NaN,36.2000,NaN,28.0000,NaN,NaN,NaN,NaN,NaN,NaN,0.0900,0,NaN,NaN,NaN,0.3400,0.0000,61.6000,0.6700,NaN,40.3000,NaN,0.4600,60.9000,NaN,NaN,64.6000,NaN,9.0000,45.7000,1719.0000,86.4000,NaN,NaN,0.0900,0.8500,NaN,46.3000,43.0000,93.0000,NaN,0.2700,0.0000,0.0000,NaN,NaN,0.0300,0.7900,NaN,0.0000,0.0000,0,NaN,0.4300,0.4300,50.0000
4,4,FW,22.0000,1,45,0.5000,0.0000,0.0000,0.0000,0.0000,0,0,0.0000,0.0000,0,0,4.0000,12.0000,333,48,0.0000,2.0000,4.0000,50,2.0000,6.0000,333.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,12.0000,12.0000,0.0000,0.0000,0.0000,6.0000,0.0000,2.0000,0.0000,0.0000,0.0000,0.0000,10.0000,0.0000,2.0000,12.0000,0.0000,0.0000,0.0000,0.0000,4.0000,0.0000,0.0000,4.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0,0.0000,0.0000,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,2.0000,0.0000,2.0000,28.0000,2.0000,NaN,0.0000,22.0000,6.0000,2.0000,0.0000,0,2.0000,0.0000,0.0000,0.0000,0.0000,24.0000,0.0000,0.0000,10.0000,18.0000,6.0000,24.0000,0.0000,0.0000,0.0000,0.0000,0.0000,18.0000,118.0000,18.0000,0.0000,2.0000,0.0000,8.0000,0.0000,24.0000,16.0000,667.0000,4.0000,0.0000,0.0000,0.0000,2.0000,0.0000,0.0000,2.0000,0.0000,0.0000,0.0000,0,4.0000,2.0000,0.0000,100.0000

In [470]:
df.fillna(0.0, inplace = True)

In [471]:
df.isnull().sum()

Id         0
Pos        0
Age        0
Starts     0
Min        0
          ..
OG         0
Recov      0
AerWon     0
AerLost    0
AerWon%    0
Length: 137, dtype: int64

In [472]:
for i in df:
    if i == "Pos":
        continue
    else:
        df[i] = df[i].astype(float)

In [473]:
for i in df:
    if (i == "Pos") | (i == "Id"):
        continue
    else:
        df[f"{i}_s"] = MinMaxScaler(feature_range = (0,1)).fit(df[[i]]).transform(df[[i]])

In [474]:
def_df = pd.DataFrame()
def_df["Id"] = df["Id"]
def_df["Pos"] = df["Pos"]
#Bloklar
def_df["Blok"]= df["Blocks_s"]*30/100 + df["BlkSh_s"]*20/100 + df["BlkShSv_s"]*25/100 + df["BlkPass_s"]*25/100  
#Müdahale
def_df["Baskı"]= df["Tkl_s"]*10/100 + df["TklWon_s"]*10/100 + df["TklDef3rd_s"]*14/100 +  \
df["TklDriAtt_s"]*12/100 + df["TklDri%_s"]*12/100 + df["Press_s"]*10/100 + \
df["PresDef3rd_s"]*14/100 + df["PresMid3rd_s"]*6/100 + df["TklW_s"]*12/100

def_df["Pas"] = df["PasTotPrgDist_s"]*8/100 + df["PasLonCmp_s"]*10/100 + df["PasAss_s"]*8/100 + df["Pas3rd_s"]*8/100 + \
df["PPA_s"]*10/100 + df["CrsPA_s"]*10/100 + df["PasAtt_s"]*10/100 + df["PasLive_s"]*10/100 + \
df["PasPress_s"]*10/100 + df["Sw_s"]*8/100 + df["Rec_s"]*8/100

def_df["Gole_katkı"] = df["Goals_s"]*70/100 + df["Assists_s"]*30/100
def_df["Dakika"] = df["Min_s"]
#new_df["new_rate"] = new_df["bloklar"]*30/100 + new_df["muda_muca"]*35/100 + new_df["pas"]* 25/100 + new_df["gole_katki"]*10/100

In [475]:
def_df = def_df[(def_df["Pos"]=="DF")|(def_df["Pos"]== "MFDF")|(def_df["Pos"]== "DFFW")|(def_df["Pos"]== "DFMF")]

In [476]:
def_df = info_df.merge(def_df, how = "left",on = "Id" )

In [477]:
def_df.head()

   Id               Name Nation           Team          League  Born  Mac  Pos   Blok  Baskı    Pas  Gole_katkı  Dakika
0   0         Max Aarons    ENG   Norwich City  Premier League  2000   34   DF 0.0515 0.0766 0.0741      0.0018  0.8424
1   1   Yunis Abdelhamid    MAR          Reims         Ligue 1  1987   34   DF 0.0412 0.0676 0.0798      0.0442  0.8722
2   2  Salis Abdul Samed    GHA  Clermont Foot         Ligue 1  2000   31  NaN    NaN    NaN    NaN         NaN     NaN
3   3    Laurent Abergel    FRA        Lorient         Ligue 1  1993   34  NaN    NaN    NaN    NaN         NaN     NaN
4   4        Charles Abi    FRA  Saint-…tienne         Ligue 1  2000    1  NaN    NaN    NaN    NaN         NaN     NaN

In [478]:
def_df.dropna(inplace=True)

In [479]:
def_df = def_df[def_df["Mac"]>10]

In [480]:
def_df.head()

    Id                  Name Nation          Team          League  Born  Mac Pos   Blok  Baskı    Pas  Gole_katkı  Dakika
0    0            Max Aarons    ENG  Norwich City  Premier League  2000   34  DF 0.0515 0.0766 0.0741      0.0018  0.8424
1    1      Yunis Abdelhamid    MAR         Reims         Ligue 1  1987   34  DF 0.0412 0.0676 0.0798      0.0442  0.8722
9    9      Francesco Acerbi    ITA         Lazio         Serie A  1988   30  DF 0.0080 0.0857 0.1195      0.1032  0.7414
12  12          Marcos AcuÒa    ARG       Sevilla         La Liga  1991   31  DF 0.0032 0.0720 0.1600      0.0331  0.6607
21  21  Martin Agirregabiria    ESP        AlavÈs         La Liga  1996   24  DF 0.0034 0.0614 0.0719      0.0018  0.4724

In [481]:
#def_df.to_csv("defans_df.csv")

In [482]:
#PasTotPrgDist : Tamamlanan pasların rakibin kalesine kat ettiği yard cinsinden toplam mesafe
#PasLonCmp : Tamamlanan paslar (30 yarddan uzun paslar)
#PasAss : Doğrudan bir şuta yol açan paslar (destekli şutlar)
#Pas3rd : Sahanın kaleye en yakın 1/3'lük kısmına giren tamamlanmış paslar
#PPA : 18 yarda ceza sahasına tamamlanmış paslar
#CrsPA : 18 yard ceza sahasına yapılan ortalar
#PasAtt : Geçiş denendi
#PasLive : Canlı top pasları
#PasPress : Rakibin baskısı altındayken yapılan paslar
#Sw : Saha genişliğinin 40 metreden fazla kat ettiği paslar

#Rec : Bir oyuncunun başarılı bir şekilde pas alma sayısı

#Tkl : Mücadele edilen oyuncu sayısı
#TklWon : Mücadeleyi yapanın takımının topa sahip olduğu müdahaleler
#TklDef3rd : Savunmada müdahale 1/3
#TklMid3rd : Ortada müdahale eder 1/3
#TklDri : Müdahale edilen driplingci sayısı
#TklDriAtt : Geçmiş top sürme sayısı artı top çalma sayısı
#TklDri% : Engellenen driplingcilerin yüzdesi
#Press : Topu alan, taşıyan veya bırakan rakip oyuncuya baskı uygulama sayısı
#PresDef3rd : Savunmada topu alan, taşıyan veya bırakan rakip oyuncuya baskı uygulama sayısı 1/3
#PresMid3rd : Ortada topu alan, taşıyan veya bırakan rakip oyuncuya baskı uygulama sayısı 1/3
#TklW : Müdahale edenin takımının topa sahip olduğu müdahaleler

#Blok
#Bloklar : Yolunda durarak topu bloke etme sayısı
#BlkSh : Yolunda durarak bir şutu engelleme sayısı
#BlkShSv : Hedefe giden bir şutu yolunda durarak engelleme sayısı
#BlkPass : Yolunda durarak bir geçişi engelleme sayısı

#Int : Yakalamalar

## OrtaSaha
---

In [483]:
ort_df = pd.DataFrame()
ort_df["Id"] = df["Id"]
ort_df["Pos"] = df["Pos"]
#Dripling
ort_df["Dripling"]= df["GcaDrib_s"]*30/100 + df["ScaDrib_s"]*20/100 + df["DriPast_s"]*25/100 +\
df["DriMegs_s"]*10/100  + df["CarProg_s"]*15/100
#press
ort_df["Press"]= df["Tkl_s"]*9/100 + df["TklWon_s"]*9/100 + df["Int_s"]*9/100 +\
df["TklDriAtt_s"]*9/100 + df["TklDri_s"]*9/100 + df["Press_s"]*9/100 + df["TklMid3rd_s"]*9/100 + \
df["PresMid3rd_s"]*10/100 + df["TklW_s"]*9/100 + df["Blocks_s"]*9/100 + df["BlkPass_s"]*9/100 
#pass
ort_df["Pas"] = df["PasAss_s"]*15/100 + df["Pas3rd_s"]*15/100 + \
df["PPA_s"]*15/100 + df["CrsPA_s"]*10/100 + df["PasAtt_s"]*10/100 + df["PasLive_s"]*10/100 + \
df["PasPress_s"]*15/100 +  df["Rec_s"]*10/100
#şut
ort_df["Şut"] = df["SoT_s"]*30/100 + df["G/Sh_s"]*25/100 +df["GcaSh_s"]*25/100 + df["ScaSh_s"]*20/100 
#Gole Katkı
ort_df["Gole_katkı"] = df["Goals_s"]*70/100 + df["Assists_s"]*30/100
ort_df["Dakika"] = df["Min_s"]

In [484]:
ort_df = ort_df[(ort_df["Pos"]== "MF")|(ort_df["Pos"]== "MFFW")]

In [485]:
ort_df.head()

        Id   Pos  Dripling  Press    Pas    Şut  Gole_katkı  Dakika
2   2.0000    MF    0.0074 0.0231 0.0971 0.0257      0.0295  0.7198
3   3.0000    MF    0.0159 0.0252 0.0889 0.0037      0.0018  0.8643
10 10.0000  MFFW    0.0716 0.0448 0.0425 0.1369      0.0102  0.0755
11 11.0000    MF    0.0300 0.2430 0.1416 0.0000      0.0000  0.0026
14 14.0000    MF    0.0231 0.0048 0.0949 0.0014      0.0021  0.3949

In [486]:
ort_df = info_df.merge(ort_df, how = "left",on = "Id" )

In [487]:
ort_df.head()

   Id               Name Nation           Team          League  Born  Mac  Pos  Dripling  Press    Pas    Şut  Gole_katkı  Dakika
0   0         Max Aarons    ENG   Norwich City  Premier League  2000   34  NaN       NaN    NaN    NaN    NaN         NaN     NaN
1   1   Yunis Abdelhamid    MAR          Reims         Ligue 1  1987   34  NaN       NaN    NaN    NaN    NaN         NaN     NaN
2   2  Salis Abdul Samed    GHA  Clermont Foot         Ligue 1  2000   31   MF    0.0074 0.0231 0.0971 0.0257      0.0295  0.7198
3   3    Laurent Abergel    FRA        Lorient         Ligue 1  1993   34   MF    0.0159 0.0252 0.0889 0.0037      0.0018  0.8643
4   4        Charles Abi    FRA  Saint-…tienne         Ligue 1  2000    1  NaN       NaN    NaN    NaN    NaN         NaN     NaN

In [488]:
ort_df.dropna(inplace=True)

In [489]:
ort_df = ort_df[ort_df["Mac"]>10]

In [490]:
ort_df.to_csv("orta_df.csv")

## Forvet

In [450]:
for_df = pd.DataFrame()
for_df["Id"] = df["Id"]
for_df["Pos"] = df["Pos"]
#Dripling
for_df["Dripling"] = df["GcaDrib_s"]*20/100 + df["ScaDrib_s"]*15/100 + df["DriPast_s"]*14/100 + df["TouAttPen_s"]*10/100 +\
df["DriMegs_s"]*3/100  + df["CarProg_s"]*8/100 + df["CarPrgDist_s"]*8/100 + df["Car3rd_s"]*12/100 + df["TouAtt3rd_s"] * 10/100
#press
for_df["Press"]= df["Tkl_s"]*10/100 + df["TklWon_s"]*16/100 + df["Int_s"]*5/100 +\
df["TklDriAtt_s"]*5/100 + df["TklDri_s"]*5/100 + df["Press_s"]*20/100  + \
df["PresMid3rd_s"]*15/100 + df["TklW_s"]*8/100 + df["Blocks_s"]*8/100 + df["BlkPass_s"]*8/100
#pass
for_df["Pas"] = df["PasAss_s"]*13/100 + df["Pas3rd_s"]*10/100 + \
df["PPA_s"]*13/100 + df["PasAtt_s"]*10/100 + df["PasLive_s"]*10/100 + \
df["PasPress_s"]*10/100 +  df["Rec_s"]*17/100 +  df["RecTarg_s"]*17/100
#şut
for_df["Şut"] = df["SoT_s"]*40/100 + df["G/Sh_s"]*25/100 +df["GcaSh_s"]*20/100 + df["ScaSh_s"]*15/100 
#Gole Katkı
for_df["Gole_katkı"] = df["Goals_s"]*80/100 + df["Assists_s"]*20/100
for_df["Dakika"] = df["Min_s"]

In [451]:
for_df = for_df[(for_df["Pos"]== "FW")|(for_df["Pos"]== "FWMF")|(for_df["Pos"]== "FWDF")]

In [452]:
for_df = info_df.merge(for_df, how = "left",on = "Id" )

In [453]:
for_df.dropna(inplace=True)

In [454]:
for_df=for_df[for_df["Mac"]>10]
for_df.head()

    Id            Name Nation            Team          League  Born  Mac   Pos  Dripling  Press    Pas    Şut  Gole_katkı  Dakika
5    5  Dickson Abiama    NGA  Greuther F¸rth      Bundesliga  1998   24    FW    0.0194 0.0578 0.0668 0.0454      0.0024  0.2121
7    7   Tammy Abraham    ENG            Roma         Serie A  1997   37    FW    0.0239 0.0326 0.0440 0.0997      0.0445  0.9017
13  13       Che Adams    SCO     Southampton  Premier League  1996   30    FW    0.0194 0.0217 0.0485 0.0494      0.2637  0.5961
15  15  Sargis Adamyan    ARM      Hoffenheim      Bundesliga  1993   13  FWMF    0.1005 0.0020 0.0368 0.1208      0.2274  0.0965
17  17      Amine Adli    FRA      Leverkusen      Bundesliga  2000   25  FWMF    0.0477 0.0000 0.1270 0.0507      0.1796  0.3671

In [455]:
for_df.to_csv("forvet_df.csv")